### ISSUE TITLE
Некоректное отображение кнопок при нажатии на меню пользователя

### ISSUE THREAD

**Issue by bladeroot** [hiqdev/yii2-theme-adminlte#1]
При нажатии на меню пользователя надписи на личных кнопках не отображаются

![screenshot_2017-05-18-10-01-10](https://cloud.githubusercontent.com/assets/10207103/26190274/415013a8-3bb1-11e7-9642-d2b962ecb554.png)

**Comment by tafid** [comment]
Fixed
